version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_SERVER=host.docker.internal
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=Poly.9800
      - DB_NAME=CEDS-NDS-V7_1
    command: nodemon server.js
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
